default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  database: notes
  pool: 5
  host: YOUR_HOST
  username: YOUR_POSTGRE_USERNAME
  password: YOUR_POSTGRE_PASSWORD
  
development:
  adapter: postgresql
  encoding: unicode
  database: notes
  pool: 5
  host: YOUR_HOST
  username: YOUR_POSTGRE_USERNAME
  password: YOUR_POSTGRE_PASSWORD

