# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: "ec2-54-163-236-33.compute-1.amazonaws.com"
  encoding: unicode
  database: ddannjcacb38du
  user: caswczlngqunnk
  password: 01ed83216e43ad80f285d0eed6b1a81e01226c6d73d955de83636afe6d516065
  port: 5432
  
development:
  adapter: postgresql
  encoding: unicode
  database: notes
  pool: 5
  host: "172.17.0.2"
  username: postgres
  password: root

